data:
    validation: 
        num_images: 10
    channels: 1
    name: 'DiskDistributedEllipsesDataset'
    im_size: 256
    length: 10000
    num_n_ellipse: 140 
    diameter: 0.4745
    batch_size: 1
forward_op:
    trafo_name: "MulticoilMRI"
training:
    epochs: 100
    log_freq: 25
    lr: 1e-4
    ema_decay: 0.999
    ema_warm_start_steps: 400 # only start updating ema after this amount of steps 
    save_model_every_n_epoch: 25
validation: 
    batch_size: 6
    snr: 0.05
    num_steps: 100
    eps: 1e-3
    sample_freq: 0 #1 # 0 = NO VALIDATION SAMPLES DURING TRAINING
model:
    type: 'openai'
    in_channels: 1
    out_channels: 1
    num_channels: 256
    num_heads: 4
    num_res_blocks: 1
    attention_resolutions: '16'
    dropout: 0.0
    resamp_with_conv: True
    learn_sigma: False
    use_scale_shift_norm: true
    use_fp16: false
    resblock_updown: true
    num_heads_upsample: -1
    var_type: 'fixedsmall'
    num_head_channels: 64
    image_size: 256
    use_new_attention_order: false
sde:
    type: ddpm
    beta_schedule: linear
    beta_min: 0.0001
    beta_max: 0.02
    num_steps: 1000

sampling:
    batch_size: 1
    eps: 0.001
    travel_length: 1
    travel_repeat: 1
seed: 10
device: cuda