data:
    validation: 
        num_images: 10
model:
    type: 'openai'
    in_channels: 1
    out_channels: 2
    num_channels: 256
    num_heads: 4
    num_res_blocks: 1
    attention_resolutions: '16'
    dropout: 0.0
    resamp_with_conv: True
    learn_sigma: True
    use_scale_shift_norm: true
    use_fp16: false
    resblock_updown: true
    num_heads_upsample: -1
    var_type: 'fixedsmall'
    num_head_channels: 64
    image_size: 256
    use_new_attention_order: false
sde:
    type: ddpm
    beta_schedule: linear
    beta_min: 0.0001
    beta_max: 0.02
    num_steps: 1000

sampling:
    batch_size: 1
    eps: 0.001
    travel_length: 1
    travel_repeat: 1
seed: 10
device: cuda